version: "3.7"

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/favorite-books/
        ports:
            - 3000:3000

    favorite-books-database:
        image: mongo:5
        ports:
            - 27017:27017
